[env:stm32g030j6_cmsis]
platform = ststm32
board = nucleo_g031k8
framework = stm32cube

; Явно указываем ваш чип в корпусе SO8N
board_build.mcu = stm32g030j6m6
board_build.f_cpu = 64000000L

; Отключаем сборку драйверов HAL, оставляем только CMSIS
build_unflags = -DUSE_HAL_DRIVER
build_flags = 
    -DSTM32G030xx

; Настройки для прошивки через ST-Link
upload_protocol = stlink
debug_tool = stlink
